service: EasyMetaFields

provider:
  name: aws
  runtime: go1.x
  stage: prod
  region: eu-west-1

  environment:
    SHOPIFY_API_KEY: ${ssm:/${self:service}/${self:provider.stage}/SHOPIFY_API_KEY}
    SHOPIFY_API_SECRET: ${ssm:/${self:service}/${self:provider.stage}/SHOPIFY_API_SECRET}
    SHOPIFY_SCOPE: "read_script_tags,write_script_tags,read_orders,write_orders,read_products,write_products"
    DYNAMODB_TABLE: "easymetafields"

package:
  exclude:
    - .gitignore
    - serverless.yml
    - node_modules
    - src
  include:
    - auth

functions:

  index:
    handler: index
    name: ${self:provider.environment.DYNAMODB_TABLE}_index
    description: First step of the OAuth Handshake
    events:
      - http:
          path: /
          method: get
          cors: true

  auth:
    handler: auth
    name: ${self:provider.environment.DYNAMODB_TABLE}_auth
    description: First step of the OAuth Handshake
    events:
      - http:
          path: /auth
          method: get
          cors: true

  auth_callback:
    handler: auth
    name: ${self:provider.environment.DYNAMODB_TABLE}_auth_callback
    description: Callback function for the OAuth Handshake
    events:
      - http:
          path: /auth/callback
          method: get
          cors: true


resources:
  Resources:
    ShopsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}

        AttributeDefinitions:
          -
            AttributeName: shopid
            AttributeType: S

        KeySchema:
          -
            AttributeName: shopid
            KeyType: HASH

        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

  Outputs:
    ShopsTable:
      Description: "The name of the Shops Table"
      Value:
        Ref: ShopsTable
    ShopsTableArn:
      Description: "The ARN for the Shops Table"
      Value:
        Fn::GetAtt:
          - ShopsTable
          - Arn
