AWSTemplateFormatVersion: 2010-09-09
Description: The AWS template for this Serverless Shopify application
Resources:
  CloudFrontOriginAccessIdentity:
    Type: 'AWS::CloudFront::CloudFrontOriginAccessIdentity'
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: CloudFront origin access identity

  CloudFrontDistribution:
    Type: 'AWS::CloudFront::Distribution'
    DependsOn:
      - S3Bucket
      - CloudFrontOriginAccessIdentity
    Properties:
      DistributionConfig:
        Enabled: 'true'
        Origins:
          - Id: !Ref S3Bucket
            DomainName: !Join
              - .
              - - !Ref S3Bucket
                - s3.amazonaws.com
            S3OriginConfig:
              OriginAccessIdentity: !Join
                - /
                - - origin-access-identity/cloudfront
                  - !Ref CloudFrontOriginAccessIdentity
        PriceClass: PriceClass_100
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          ViewerProtocolPolicy: redirect-to-https
          TargetOriginId: !Ref S3Bucket
          ForwardedValues:
            QueryString: false
        DefaultRootObject: index.html
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html

  S3BucketPolicy:
    DependsOn:
      - S3Bucket
      - CloudFrontOriginAccessIdentity
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
          Action:
            - 's3:GetObject'
            - 's3:ListBucket'
          Effect: Allow
          Resource:
            - !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref S3Bucket
            - !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref S3Bucket
                - /*
          Principal:
            AWS: !Join
              - ' '
              - - 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity'
                - !Ref CloudFrontOriginAccessIdentity
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: 123-test-bucket-123
      AccessControl: Private
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

